### ISSUE TITLE
Milvus version problem

### ISSUE THREAD

**Issue by z2labplus** [zilliz-bootcamp/video_analysis#2]
Click the link in the past, and you can't find the installation steps of Milvus 0.11.0 on the official website

**Comment by miia12** [comment]
We released milvusv1.0 last week, and we won't maintain later versions. So you need to change milvus and corresponding codes.

**Comment by HoangTienDuc** [comment]
hello, i tried to used milvus 1.1.0 to create a coolection
```
import collections
from milvus import Milvus, DataType
from common.config import MILVUS_HOST, MILVUS_PORT, TOP_K


milvus = Milvus(host=MILVUS_HOST, port=MILVUS_PORT)

def create_table(client, table_name, dimension):
    collection_param = {
    "fields": [
        {"name": "embedding", "type": DataType.FLOAT_VECTOR, "params": {"dim": dimension}},
    ],
    "segment_row_limit": 800000,
    "auto_id": True
    }
    try:
        status = client.create_collection(table_name, collection_param)
        return status
    except Exception as e:
        print("Milvus ERROR:", e)

create_table(milvus, 'test_db', 512)
```
but it fail
```
Traceback (most recent call last):
  File "tmp.py", line 2, in <module>
    from milvus import Milvus, DataType
ImportError: cannot import name 'DataType'
```

**Comment by pokerc** [comment]
> hello, i tried to used milvus 1.1.0 to create a coolection
> 
> ```
> import collections
> from milvus import Milvus, DataType
> from common.config import MILVUS_HOST, MILVUS_PORT, TOP_K
> 
> 
> milvus = Milvus(host=MILVUS_HOST, port=MILVUS_PORT)
> 
> def create_table(client, table_name, dimension):
>     collection_param = {
>     "fields": [
>         {"name": "embedding", "type": DataType.FLOAT_VECTOR, "params": {"dim": dimension}},
>     ],
>     "segment_row_limit": 800000,
>     "auto_id": True
>     }
>     try:
>         status = client.create_collection(table_name, collection_param)
>         return status
>     except Exception as e:
>         print("Milvus ERROR:", e)
> 
> create_table(milvus, 'test_db', 512)
> ```
> 
> but it fail
> 
> ```
> Traceback (most recent call last):
>   File "tmp.py", line 2, in <module>
>     from milvus import Milvus, DataType
> ImportError: cannot import name 'DataType'
> ```

same import error in pymilvus 1.1.2, any solutions?
